name: Build and Test
on:
  pull_request:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      postgres-db:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgresql
          POSTGRES_USER: postgresql
          POSTGRES_PASSWORD: postgresql
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Build
        run: ./gradlew build
      - name: Run in background
        run: ./gradlew bootRun &
        env:
          SPRING_PROFILES_ACTIVE: postgresql
      - name: Install HawkScan
        uses: stackhawk/hawkscan-action@v2
        with:
          installCLIOnly: true
      - name: HawkScan Scan
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: hawk ${{ secrets.COMMAND_LINE_ARGS }} --api-key=${{ secrets.HAWK_API_KEY_TEST }} scan stackhawk.d/stackhawk-openapi.yml stackhawk-all-the-scans.yml
